services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  traefik-public:
    external: false
